In [1]:
l = [23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

-----------------

In [9]:
a[2:]

array([  546,   215, -1234])

In [10]:
a[2:4]

array([546, 215])

In [16]:
b = a[2:4]  # this does not create a copy, it is a view to array a... and is recursive... 

In [12]:
b 

array([546, 215])

In [13]:
b[:] = 111

In [14]:
b

array([111, 111])

In [15]:
a

array([23245,    27,   111,   111, -1234])

In [25]:
c = a.copy()

In [26]:
c

array([23245,    27,   111,   111, -1234])

In [27]:
c[0] = 0

In [28]:
c

array([    0,    27,   111,   111, -1234])